### ISSUE TITLE
Notification bar is not vietnamese

### ISSUE THREAD

**Issue by aaaahoang123** [Belmont-Gabriel/MIUI-6-XML-Vietnamese#3]
please update language for new version of miui, the notification now is english...

**Comment by Belmont-Gabriel** [comment]
Keep calm, we're working :D

**Comment by aaaahoang123** [comment]
Hehe, i am hoping for a perfect vietnamese miui :D

**Comment by HuySpin** [comment]
@aaaahoang123 keep calm!
